V3
webtoolbox/craftcms-plugin pull request #6
Opened 2023-04-21 11:26 UTC by kishanm-wtbx

For review: 
- Add error handler for API calls to avoid undefined variable error.
- Change to load embedded code script

Ticket Link: [Client Ticket Link](https://www.websitetoolbox.com/tool/ticket/view/51030/36zKhmVI4uAtv9YyWaNw)

Tester Name: -

2023-04-21 12:30 UTC, webtoolbox requested changes

2023-04-21 12:30 UTC, webtoolbox commented on .craftplugin
> +{"pluginName":"Website Toolbox Community","pluginDescription":"Your CraftCMS community doesn’t need to be basic. Website Toolbox is a cloud-based community plugin that allows you to easily add a powe
Use the description that was approved for version 4.

2023-04-21 12:30 UTC, webtoolbox commented on README.md
> +Click here -> [Website Toolbox Community Documentation](https://websitetoolbox.com/plugins/websitetoolboxforum/documentation)
This link does not exist! Feedback was already given on that previously. Remove it.

2023-04-21 12:30 UTC, webtoolbox commented on composer.json
> +    "description": "Your CraftCMS community doesn’t need to be basic. Website Toolbox is a cloud-based community plugin that allows you to easily add a powerful, intuitive, and maintenance-free commu
Use the previously approved description.

2023-04-21 13:07 UTC, webtoolbox approved these changes, later dismissed

2023-04-25 11:47 UTC, masihur submitted a review, later dismissed
In Some places you are using community and on some places you are using forum. Please check it properly.

2023-04-25 11:55 UTC, kishanm-wtbx commented
It is because of craftcms support team suggest us to keep the plugin handle name same as we have in earlier version. We can change plugin name but cannot change plugin handle name. If we change the handle name then we have to launch the plugin as completely new. That is the reason to code contain forum at some place and community at rest place.

2023-04-25 12:12 UTC, webtoolbox approved these changes, later dismissed

2023-04-25 12:23 UTC, kishanm-wtbx commented
Sandeep Sir,

As per the craftcms support team, we need to keep separate branches for version 3 and version 4. So merge request is not require from my side. You can link/upload the v3 brach to craftcms store. It may be done from craftcms store account.

2023-05-04 05:15 UTC, kishanm-wtbx commented
The v3 branch itself a branch for craftcms version 3 plugin. It has been reviewed by Sandeep sir and Masihur sir. The pull request no need to merge with any other branch. So, I close it.

2023-05-04 05:15 UTC, closed without merging